### PR TITLE
document second parameter to custom_columns's transform method

### PR DESCRIPTION
**Pull request by joshrabinowitz**
For https://github.com/bigpresh/Dancer-Plugin-SimpleCRUD/issues/62

### CODE REVIEW

**Comment by bigpresh** [comment]
Bugger - I didn't see this until after I made similar changes in 72ece79. sorry!

I'll close this one since I've already documented it (and referred to the details on callbacks in HTML::Table::FromDatabase's documentation)

**Comment by joshrabinowitz** [comment]
Hm, I just looked at the current master docs and there's no explicit mention of a second parameter passed to the transform subref. I'm not positive it still merges cleanly but I think this diff should get committed unless there's some reason to not document the second parameter explicitly?

**Comment by bigpresh** [comment]
The docs I added in 72ece79 include:

> In particular, the coderef will receive the value of the
+column as the first parameter, but also a reference to the whole row hashref
+as the second parameter, so you can do a variety of cunning things.

That seems clear enough, no?

**Comment by joshrabinowitz** [comment]
@bigpresh oh I had missed that, I do see that text in your commit 72ece79 -- but I don't see it in master here https://github.com/bigpresh/Dancer-Plugin-SimpleCRUD/blob/master/lib/Dancer/Plugin/SimpleCRUD.pm

**Comment by joshrabinowitz** [comment]
Also I think it would be nice to document it in the code sample for the cut&pasters. Specifically https://github.com/bigpresh/Dancer-Plugin-SimpleCRUD/pull/66/files#diff-cec81528392d0cbdf55fe4d00bb0775aL130

**Comment by bigpresh** [comment]
Ah yes - that commit is in PR #68, which I've not merged yet, as I wanted to make sure it's all working right, and give a chance for feedback.

Speaking of which, many, many thanks for your contributions lately, both code-wise and ideas & review - it's appreciated.  I assume you saw I added you as a collaborator on the repo to make life easier? :)

**Comment by joshrabinowitz** [comment]
Glad to contribute. Thank you in return for your work on Dancer. 
I did not notice you had added me as a contributor, that is appreciated.

**Comment by joshrabinowitz** [comment]
Also not to beat a dead horse but I was talking specifically about line 130 of that diff.

**Pull request closed without merging**
