### PR TITLE
SECURITY: Fix misused _ensure_auth calls

### PR DESCRIPTION
**Pull request by bigpresh**
Oh, man.

Some places called `_ensure_auth()` in void context, presumably thinking it would modify the handler coderef given to inject authentication checking - but it doesn't, `_ensure_auth()` returns a new coderef which does the required authentication checks then calls the original handler coderef which was given to `_ensure_auth()`.  So, calling it in void context then passing the original handler coderef when setting up the route means there's no actual checking done on that route.  Oops.

This is a pretty embarassing fuckup - a security problem on one of my projects.  I hold my hands up and apologise to anyone affected by this, for this is a stupid mistake.  A better test suite would have caught this.

I will see if a CVE ID is warranted for this, and apply for one if so.

Big thanks to @joshrabinowitz for finding and reporting this one, and for adding tests which demonstrated the issue.

### CODE REVIEW

**Comment by bigpresh** [comment]
This is issue #104 - further description on that ticket.

**Comment by joshrabinowitz** [comment]
thumbs up - can we merge and make a new release?

**Comment by bigpresh** [comment]
Yes!   Will try to get it out tonight.

**Comment by joshrabinowitz** [comment]
That would be very nice. Thanks @bigpresh

**Comment by joshrabinowitz** [comment]
I believe this is fixed and the code has been released to CPAN. @bigpresh can you close this issue?

**Pull request merged**
