### PR TITLE
Tests2

### PR DESCRIPTION
**Pull request by joshrabinowitz**
@bigpresh @msouth 

This improves on https://github.com/bigpresh/Dancer-Plugin-SimpleCRUD/pull/55
 - uses SQLite for testing
 - creates and tests status code for a simple_crud() route

Thoughts?

### CODE REVIEW

**Comment by bigpresh** [comment]
Looking good so far!  More comprehensive tests are going to be... fun, though :)

**Comment by joshrabinowitz** [comment]
Well thank you bigpresh. Suggestions on the (minimum) tests you'd like to see before merging this?

**Comment by joshrabinowitz** [comment]
@bigpresh not sure you saw my comment above. 
Let me know if you have suggestions for what you'd like to see tested.

**Comment by bigpresh** [comment]
Ah, sorry, missed it.

Hmm, I'd like to parse the resulting output, and test:

* all columns are present as expected
* supplied custom columns are present
* values calculated in custom columns are as expected
* add/edit/delete routes work 
* searching works
* sorting works

Might be tricky, might not be too bad.  I'll quite happily help as and when I have a moment to spare - unfortunately things are hectic for me right now :|

**Comment by joshrabinowitz** [comment]
@bigpresh this is starting to shape up. 

I have the first two of your bullet points above implemented and the others don't look far off. 

Interested in your thoughts on this and the other PRs

**Comment by joshrabinowitz** [comment]
@msouth interested in your thoughts. I think we can commit this and improve later. 

Also can squash commits if desired.

**Comment by bigpresh** [comment]
Nice!  I agree, this is good to go for now; there's a lot of room for additional testing in future, but this is already an order of magnitude more than what we have currently :)

Regarding squashing commits - personally, I don't bother, I like to be able to see the history of a feature's development and commit messages giving context to what was being done, etc.

**Comment by bigpresh** [comment]
Merged.  I think the next CPAN release should probably be a dev release to see cpantesters results, to make sure the tests don't fail on oddly-configured systems or anything like that.

**Comment by joshrabinowitz** [comment]
thanks and sounds good bigpresh

**Pull request merged**
