### PR TITLE
test on perl 5.26

### PR DESCRIPTION
**Pull request by joshrabinowitz**
latest perl is 5.26.2, after all :]

### CODE REVIEW

**Comment by joshrabinowitz** [comment]
@bigpresh this seems like a good time to merge this too

**Comment by bigpresh** [comment]
OOI, what's the rationale behind skipping 5.14, rather than the oldest (or, just testing them all)?

**Comment by joshrabinowitz** [comment]
I wanted to leave 5 versions of perl because Travis-C runs 5 children at once per repo. 

Therefore if we test 6 versions, the CI tests will take almost 2x as long (because the 6th test doesn't start up until one of the first 5 test is done).

**Comment by joshrabinowitz** [comment]
As for not dropping the oldest, I assumed that 5.14 was the earliest version already for a reason -perhaps it was the earliest supported version of perl

**Comment by bigpresh** [comment]
The diff suggests 5.12 and 5.10 are still there - so it seems weird to test those, skip 5.14 and test newer version too.  Personally, I'm not that fussed about the build time - are you?  I'd rather have wider coverage than faster CI builds.

**Comment by joshrabinowitz** [comment]
Works for me. What's the 'earliest supported version of perl' for ::SC?

**Comment by joshrabinowitz** [comment]
@bigpresh just a reminder - shall we merge

**Pull request merged**
