### PR TITLE
add custom_column "column_class" feature

### PR DESCRIPTION
**Pull request by joshrabinowitz**
Also show any captured errors.

### CODE REVIEW

**Comment by joshrabinowitz** [comment]
bump

**Comment by bigpresh** [comment]
Bugger, sorry I was so slow with this.  We could have had 1.11 released on 11/11!

**Comment by bigpresh** [comment]
Anyway, 1.11 is finally on CPAN.

**Comment by joshrabinowitz** [comment]
Yay! Progress continues.
Can you merge PR #92 too? 
Adds testing on perl 4.24.0 to travis-ci.

**Pull request merged**
