### PR TITLE
Adds where_filter option.

### PR DESCRIPTION
**Pull request by joshrabinowitz**
@msouth @bigpresh thoughts?

### CODE REVIEW

**Comment by joshrabinowitz** [comment]
- Adds where_filter option, for easy display and 
        editing of subsets of tables. 

 =item where_filter (optional, default: '')

 Specify a where clause to use to filter the table. For example, 
    
    simple_crud(
        prefix => 'bar',
        where_filter => 'id > 1000',
        ...
    );

This would cause only rows with an id of over 1000 to be displayed.

**Comment by bigpresh** [comment]
My initial gut reaction was "ugh, passing in SQL - I'd rather it take something that could be passed to D::P::D's quick_select() etc methods", but that would possibly make it a lot more complex (but could be done, by refactoring `D::P::D::Core::Handle->_generate_sql()` to make it usable from here).

Otherwise, it'd need to be carefully documenting that you're passing in a fragment of SQL which will be used as-is in your query, and therefore be bloody careful :)

I like the idea though - there may well be cases where only a subset of the data in the table should be manageable.

**Comment by joshrabinowitz** [comment]
Thanks for the feedback, I hear you.

After I wrote this I also considered that we might want something more dynamic - like 'filter to a where clause based on the logged-in user'. Will rethink. 

Maybe something like:
  ```

  simple_crud(
    prefix=>'bar',
    where_filter => sub { if (a) { return <where-spec-structure> } } # looks at stuff to decide wherespec
  }
```

**Comment by msouth** [comment]
would something like 

`default_search=> [some search designation]`

work?  They could do a search, maybe, to learn what shows up in the url, and that way learn "organically" how to specify.

Or even

`filter => [search designation of the same type described above] # apply this filter all the time in addition to any search the user might do`

**Comment by joshrabinowitz** [comment]
@msouth, yes, I think that's very similar to what I originally suggested.

Seems like we agree the feature idea is good. I'll try to work up another patch for discussion

**Comment by joshrabinowitz** [comment]
@msouth - Should have read more carefully -  I just realized you were suggesting we define the 'filter' in terms of query string name/value pairs instead of sql semantics.

**Comment by bigpresh** [comment]
As PR-57 implements this feature via reusing code from D::P::D, this PR can be closed now, yeah?

**Comment by joshrabinowitz** [comment]
@bigpresh, yes. Was leaving it open for the discussion. Closing now.

**Pull request closed without merging**
