### PR TITLE
test on perl 5.24 too

### PR DESCRIPTION
**Pull request by joshrabinowitz**
test in travis-ci with new perl

### CODE REVIEW

**Comment by joshrabinowitz** [comment]
bump

**Comment by joshrabinowitz** [comment]
bump

**Comment by joshrabinowitz** [comment]
@bigpresh I presume this is not desired?

**Comment by bigpresh** [comment]
Hmm.  I somehow missed the previous GH emails, sorry!

I wasn't really doing much dev work over Christmas, that's my excuse :)

**Pull request merged**
